

use_viewer: True
replace_existing_results: False
write_results: True

sim_params:
  platform_height: 0.0

tags:
  results_storage_tag: 'mytag'

force_control:
  # Kp: 0.002
  # min_torque: -0.05
  Kp: 0.002
  min_torque: -0.05

dir:
  assets_dir: dgn_dataset  #'objects'
  franka_urdf: 'franka_description/robots/franka_panda_fem_simple_v4_with_arm.urdf'
  results_dir: 'results' 

data_recording:
  is_recording: False
  data_recording_path: '/home/baothach/shape_servo_data/stress_field_prediction/6polygon/test'

miscellaneous:
  force_debug: False
  force_debug_recording_path: "visualization/recorded_forces/random_tests"

franka:
  num_joints: 16
  gripper_tip_z_offset: 0.112
  gripper_tip_y_offset: 0.00444222
  joint_damping: 100

timeout:
  squeeze_no_gravity: 1000
  other_modes: 400  #600  #700

lp_filter:
  running_window_size: 50
  averaging_window: 10 

squeeze_no_gravity:
  num_dp: 50
  torque_step_period: 10
  soft_object_torque_step: 0.3
  near_rigid_object_torque_step: 0.15
  soft_object_F_des: 15
  near_rigid_object_F_des: 30

reorient:
  ang_vel: 3

lin_acc:
  max_acc: 50
  jerk: 100

ang_acc:
  travel_acc: 3
  min_travel_speed: 0.1
  max_travel_speed: 0.5
  max_acc: 1250
  jerk: 2500


